export const CATEGORIES = [
  { key: 'all', label: 'Everything' },
  { key: 'creator', label: 'For Creators' },
  { key: 'ai', label: 'AI Experiences' },
  { key: 'client', label: 'For Our Clients' },
  { key: 'gifting', label: 'Gifting' },
];

export const PRODUCTS = [
  {
    slug: 'film-essence-presets',
    name: 'The Film Essence Presets',
    category: 'creator',
    tagline: 'BESTSELLER',
    price: 45,
    compareAt: null,
    blurb: '5 Lightroom Mobile & Desktop presets formulated for golden-hour skin tones and nostalgic film textures.',
    includes: [
      '5 signature presets: Halton Film, Golden Hour Glow, Heirloom Mono + 2 seasonal variants',
      'Both XMP (Desktop/ACR) and DNG (Mobile) formats for every preset',
      'Step-by-step install guides for iPhone, Android, Lightroom Desktop & Adobe Camera Raw',
      'Hafsa\u2019s shooting notes — the light each grade was born from',
      'Lifetime updates — every future refinement lands in your inbox',
    ],
    steps: ['Pay securely by card', 'Instant download link by email', 'Import in under 2 minutes with the guide'],
    delivery: 'Instant download · XMP + DNG · lifetime updates',
    preview: '/images/corridor/corridor-1.jpg',
    presets: ['halton-film', 'golden-hour-glow', 'heirloom-mono'],
  },
  {
    slug: 'master-cinematic-suite',
    name: 'Master Cinematic Suite',
    category: 'creator',
    tagline: 'PRO SUITE',
    price: 89,
    compareAt: 137,
    blurb: '15 complete presets: Golden Hour, Moody 35mm, Light & Airy, and Archival Black & White Fine Art.',
    includes: [
      'All 15 presets across 4 collections: Golden Hour, Moody 35mm, Light & Airy, Archival B&W',
      'XMP + DNG for every preset (desktop and mobile)',
      'Hafsa\u2019s full grading workflow notes (PDF companion)',
      'Install guides for iOS, Android, Desktop, ACR',
      'Lifetime updates + first access to new collections',
    ],
    steps: ['Pay securely by card', 'Instant download by email', 'Follow the suite guide to build your signature look'],
    delivery: 'Instant download · XMP + DNG · installation guides for iOS, Android, Desktop & ACR',
    preview: '/images/corridor/corridor-2.jpg',
    presets: ['halton-film', 'muskoka-autumn', 'paletta-lakefront', 'gairloch-rose', 'studio-high-key'],
  },
  {
    slug: 'cinematic-luts',
    name: 'Cinematic Reel LUT Pack',
    category: 'creator',
    tagline: 'FOR VIDEO',
    price: 39,
    compareAt: null,
    blurb: '8 .cube LUTs graded from Hafsa\'s film looks — for Premiere, Final Cut, DaVinci & CapCut.',
    includes: [
      '8 .cube LUTs: Golden Hour, Muskoka Autumn, Heirloom Mono, Halton Film + 4 more',
      'Rec.709 versions for standard footage and Rec.2020 variants for log/RAW',
      'Strength guide: how far to push each look on phone vs camera footage',
      'Import instructions for Premiere, Final Cut, DaVinci Resolve & CapCut',
    ],
    steps: ['Pay securely by card', 'Instant download by email', 'Drop the .cube into your editor and grade'],
    delivery: 'Instant download · .cube format · Rec.709 & Rec.2020 variants',
    preview: '/images/corridor/corridor-3.jpg',
  },
  {
    slug: 'grain-light-overlays',
    name: 'Grain & Light-Leak Overlays',
    category: 'creator',
    tagline: 'TEXTURES',
    price: 29,
    compareAt: null,
    blurb: '24 archival 4K overlays — 35mm grain, halation blooms, anamorphic flares, and dusty light leaks.',
    includes: [
      '24 overlays in 4K: fine & coarse 35mm grain, halation blooms, anamorphic flares, dust & leak textures',
      'ProRes 422 HQ for video editors + PNG sequences for photo compositing',
      'Blend-mode cheat sheet (Screen, Add, Soft Light) with recommended opacities',
    ],
    steps: ['Pay securely by card', 'Instant download by email', 'Layer over any frame and set the blend mode'],
    delivery: 'Instant download · 4K ProRes + PNG sequences',
    preview: '/images/corridor/corridor-4.jpg',
  },
  {
    slug: 'prompt-vault',
    name: 'The Prompt Vault',
    category: 'creator',
    tagline: 'AI GRADE',
    price: 35,
    compareAt: null,
    blurb: '120+ master prompts: posing direction, editing language, and AI image recipes distilled from the atelier.',
    includes: [
      '120+ tested prompts across posing direction, editing language, and image generation',
      'Organised Notion vault + printable PDF (both included)',
      'Hafsa\u2019s personal adaptation notes for each prompt family',
      'Free lifetime additions — the vault grows, you keep access',
    ],
    steps: ['Pay securely by card', 'Instant PDF + Notion link by email', 'Duplicate the vault into your workspace'],
    delivery: 'Instant PDF + Notion vault · free lifetime additions',
    preview: '/images/corridor/corridor-5.jpg',
  },
  {
    slug: 'atelier-business-kit',
    name: 'The Atelier Business Kit',
    category: 'creator',
    tagline: 'TEMPLATES',
    price: 79,
    compareAt: 129,
    blurb: 'Contract templates, pricing guide framework, and the complete client email script library.',
    includes: [
      'Photography contract templates (session, wedding, print release) in DOCX + PDF',
      'Pricing-guide framework with Hafsa\u2019s collection structure as the worked example',
      '26 client email scripts: inquiry → booking → gallery → review',
      'Ontario-ready wording notes (have counsel review before use)',
    ],
    steps: ['Pay securely by card', 'Instant download by email', 'Personalise and deploy the kit'],
    delivery: 'Instant download · DOCX + PDF · Ontario-ready wording',
    preview: '/images/corridor/corridor-6.jpg',
  },
  {
    slug: 'ai-portrait-sitting',
    name: 'AI Portrait Sitting',
    category: 'ai',
    tagline: 'EXPERIENCE IT',
    price: 65,
    compareAt: null,
    blurb: 'Upload 8–10 selfies; receive 20 cinematic portraits rendered in the atelier\'s signature golden light.',
    includes: [
      '20 finished 4K portraits in 4 atelier looks (Golden Hour, Moody Film, Editorial Mono, Studio)',
      'Private gallery link with instant download for every frame',
      '2 revision passes on your favourite 3 portraits',
      'Full personal-use licence for profiles, prints & sharing',
    ],
    steps: ['Order & upload 8–10 selfies via your private link', 'The atelier renders within 48h', 'Download from your private gallery'],
    delivery: '48h turnaround · 4K · private gallery link',
    preview: '/images/corridor/corridor-1.jpg',
    ai: 'portrait',
  },
  {
    slug: 'what-to-wear-style-report',
    name: 'What-to-Wear Style Report',
    category: 'ai',
    tagline: 'WARDROBE',
    price: 30,
    compareAt: null,
    blurb: 'A personalized wardrobe guide for your session — palette, fabrics and outfit pairs matched to your venue, season and session type.',
    includes: [
      'A personalized palette for every member of the family (harmonising, never matching)',
      '3 complete outfit pairings with shopping-list notes',
      'Venue & season adjustments (escarpment wind, lakefront glare, golden-hour warmth)',
      'The avoid-list — 6 things that quietly break a frame',
    ],
    steps: ['Order & complete the style intake on the page', 'The wardrobe intelligence drafts your guide in minutes', 'Arrives on screen and by email — take it shopping'],
    delivery: 'Minutes after intake · on screen + email · one free revision',
    preview: '/images/corridor/corridor-1.jpg',
    interactive: 'style-report',
  },
  {
    slug: 'wall-art-visualizer',
    name: 'Wall Art Visualizer',
    category: 'client',
    tagline: 'FREE EXPERIENCE',
    price: 0,
    compareAt: null,
    blurb: 'See Hafsa\u2019s museum prints on your own wall — upload a photo of your room and place true-scale art before you buy.',
    includes: [
      'Upload any room photo — drag & scale museum prints in true size',
      'Three archival sizes: 8\u00D710, 16\u00D720 (signature), 24\u00D736 statement',
      'Substrate & framing notes for each size',
      'Free — always. Take the mock-up straight to checkout.',
    ],
    steps: ['Upload your room photo', 'Drag a print into place at true scale', 'Order the size that fits — mock-up in hand'],
    delivery: 'Free interactive tool · no card required',
    preview: '/images/corridor/corridor-5.jpg',
    interactive: 'wall-visualizer',
  },
  {
    slug: 'ai-restoration',
    name: 'AI Photo Restoration',
    category: 'ai',
    tagline: 'HEIRLOOM RESCUE',
    price: 25,
    compareAt: null,
    blurb: 'Torn, faded, or water-damaged family photographs restored, colorized, and archival-grade printed on request.',
    includes: [
      'Full restoration: tears, fading, water & sun damage repaired',
      'Optional hand-tinted colorization of black-and-white originals',
      '4K digital file delivered + optional museum-grade print',
      'One revision pass included on every photo',
    ],
    steps: ['Order & upload your original (a phone photo of it is fine)', 'Restored within 24h', 'Receive the digital file — add a museum print if you wish'],
    delivery: 'Per photo · 24h · digital + optional museum print',
    preview: '/images/corridor/corridor-2.jpg',
    ai: 'restore',
  },
  {
    slug: 'once-upon-golden-hour',
    name: 'Once Upon a Golden Hour',
    category: 'ai',
    tagline: 'STORYBOOK',
    price: 95,
    compareAt: null,
    blurb: 'A personalized children\'s storybook illustrated with your own family\'s session photographs — a bedtime heirloom.',
    includes: [
      'A 24-page illustrated storybook starring your family, written from a short intake questionnaire',
      'Your own session photographs woven into every spread',
      'Digital edition (yours forever) + optional printed heirloom edition',
      'A story title chosen with your child\u2019s name in gold',
    ],
    steps: ['Order & answer the 6-question story intake', 'The draft is written, then finished by Hafsa', 'Digital delivery in 72h — print edition ships in 2 weeks'],
    delivery: 'Digital + print option · 24 pages · written & illustrated by AI, finished by Hafsa',
    preview: '/images/corridor/corridor-3.jpg',
    ai: 'storybook',
  },
  {
    slug: 'haffu-in-a-box',
    name: 'HAFFU-in-a-Box',
    category: 'ai',
    tagline: 'FOR PHOTOGRAPHERS',
    price: 29,
    compareAt: null,
    blurb: 'The white-label AI studio manager: answers inquiries, books discovery calls, and protects your creative hours — in your brand voice.',
    includes: [
      'Your own Haffu: trained on your packages, voice & FAQs',
      'Website chat widget + booking calendar hand-off',
      'Inquiry inbox triage with budget scoring',
      'Monthly tuning call to sharpen the voice',
    ],
    steps: ['Subscribe & complete the brand intake', 'We embed Haffu on your site', 'Cancel anytime — no lock-in'],
    delivery: 'Monthly subscription · embeds on any site · cancel anytime',
    preview: '/images/corridor/corridor-4.jpg',
    subscription: true,
  },
  {
    slug: 'extra-image-pack',
    name: 'Additional Image Pack',
    category: 'client',
    tagline: 'GALLERY ADD-ON',
    price: 250,
    compareAt: null,
    blurb: 'Unlock the entire unculled gallery download — every frame, hand-graded and retouched.',
    includes: [
      'Every photograph from your session — not just the curated selection',
      'Hand-graded & retouched to the same heirloom standard',
      'Private vault link, 90-day retention',
      'Organised by chapter & moment for easy browsing',
    ],
    steps: ['Order with your gallery code', 'The vault unlocks within hours', 'Download everything, forever'],
    delivery: 'Private vault link · 90-day retention',
    preview: '/images/corridor/corridor-5.jpg',
  },
  {
    slug: 'museum-print',
    name: 'Museum Fine Art Print (16×20)',
    category: 'client',
    tagline: 'ARCHIVAL',
    price: 145,
    compareAt: null,
    blurb: 'Heavyweight 100% cotton rag archival paper with deep blacks and exhibition-grade color fidelity.',
    includes: [
      'Hahnemühle-grade 100% cotton rag, 308gsm matte',
      'Archival pigment inks — rated 200+ years without fading',
      'Hand-inspected & signed certificate of authenticity',
      'Sizes: 8\u00D710 ($65) · 16\u00D720 ($145) · 24\u00D736 ($295)',
    ],
    steps: ['Choose your frame from your gallery', 'We print, inspect & sign', 'Shipped flat & protected in 5–7 days'],
    delivery: 'Shipped in 5-7 days · certificate of authenticity',
    preview: '/images/corridor/corridor-6.jpg',
  },
  {
    slug: 'gift-voucher-100',
    name: 'Digital Gift Voucher',
    category: 'gifting',
    tagline: 'GIFTING',
    price: 100,
    compareAt: null,
    blurb: 'The gift of timeless memories. Instant voucher code delivery with zero expiration.',
    includes: [
      'Instant unique voucher code by email — zero expiration',
      'Denominations: $100 / $250 / $500',
      'Personal message from you on the voucher',
      'Fully transferable — forward it to anyone',
    ],
    steps: ['Choose the denomination', 'Voucher arrives by email instantly', 'Recipient books any session or product'],
    delivery: 'Instant email · $100 / $250 / $500 denominations',
    preview: '/images/corridor/corridor-2.jpg',
    variants: [100, 250, 500],
  },
  {
    slug: 'atelier-circle',
    name: 'The Atelier Circle',
    category: 'gifting',
    tagline: 'MEMBERSHIP',
    price: 180,
    compareAt: null,
    blurb: 'Annual membership: priority booking windows, exclusive mini-session drops, member-only presets, and a handwritten anniversary note.',
    includes: [
      'Priority booking windows — first pick of golden-hour dates',
      'Two exclusive mini-session drops per year (members only)',
      'Member-only preset each season',
      'A handwritten anniversary note from Hafsa',
    ],
    steps: ['Join the Circle', 'Receive your welcome pack instantly', 'Priority windows open by email each season'],
    delivery: 'Instant welcome pack · annual',
    preview: '/images/corridor/corridor-4.jpg',
    subscription: true,
  },
];

export function getProduct(slug) {
  return PRODUCTS.find((p) => p.slug === slug) || null;
}
