// HAFFU Studio Tool Handlers

const CalendarService = require('../../calendar');
const Booking = require('../../../models/Booking');
const Client = require('../../../models/Client');
const StripeService = require('../../stripe');
const EmailService = require('../../email');
const { PACKAGES, DIGITAL_PRODUCTS, ADDONS } = require('../../../utils/constants');
const { editImage, analyzeImage } = require('../../../config/vertex');
const toolHandlers = {
  async check_availability({ date }) { return { date, ...(await CalendarService.getAvailability(date)) }; },
  async create_booking(p) { let c = await Client.findByEmail(p.clientEmail); if (!c) c = await Client.create({ name: p.clientName, email: p.clientEmail, phone: p.clientPhone }); const price = PACKAGES[p.sessionType]?.price || 0; const b = await Booking.create({ ...p, clientId: c.id, price }); return { bookingId: b.id, clientId: c.id, retainerAmount: b.retainerAmount, status: 'pending' }; },
  async send_contract({ bookingId, clientEmail }) { const b = await Booking.get(bookingId); await EmailService.sendContract(clientEmail, b.clientName, b.sessionType, b.date); return { sent: true, bookingId }; },
  async collect_payment({ bookingId, amount }) { const b = await Booking.get(bookingId); const s = await StripeService.createCheckoutSession({ ...b, retainerAmount: amount }, 'https://hafsanoreen.com/booking/confirmed', 'https://hafsanoreen.com/booking'); return { checkoutUrl: s.url }; },
  async answer_faq({ topic }) { const f = { pricing: 'Portraits $450, Families $650, Events $1200, Weddings $3800, Signature $6500. + HST.', booking: 'Book 3-6 months ahead. 30% retainer secures your date.', wardrobe: 'Personalized style guide included. Soft neutrals recommended.', delivery: 'Full gallery in 3-4 weeks. Sneak peek in 48 hours.', travel: 'No travel fees in Halton. Extended areas quoted per trip.', prints: 'Print store with fine-art prints, canvases, and albums.', products: 'Photo enhancement, gift cards, presets, wall art, mood boards, albums, save-the-date reels.' }; return { answer: f[topic] || 'Let me check that for you.' }; },
  async recommend_package({ sessionType, guestCount = 0 }) { const r = { wedding: guestCount > 150 ? 'signature' : 'wedding', family: 'family', maternity: 'family', event: 'event', portrait: 'portrait', brand: 'portrait' }; const p = PACKAGES[r[sessionType] || sessionType]; return { recommended: p?.name, price: p?.price, reason: 'Best coverage for your ' + sessionType + ' session.' }; },
  async send_reminder({ bookingId, type }) { const b = await Booking.get(bookingId); const r = { 'pre-session': { s: 'Session coming up!', b: 'Your prep guide is ready.' }, 'sneak-peek': { s: 'Sneak peek ready!', b: '5 frames from your session.' }, 'gallery-ready': { s: 'Gallery is here!', b: 'All images ready.' }, 'review-request': { s: 'Loved your photos?', b: 'Leave a review!' } }; await EmailService.send({ to: b.clientEmail, subject: r[type].s, html: '<p>' + r[type].b + '</p>' }); return { sent: true, bookingId, type }; },
  async smart_upsell({ sessionType }) { const s = []; if (sessionType === 'wedding' || sessionType === 'signature') { s.push({ ...ADDONS.reel, reason: 'Cinematic reel captures emotion.' }); s.push({ ...ADDONS.album, reason: 'Heirloom album.' }); } s.push({ ...ADDONS.extraHour, reason: 'More time = more memories.' }); return { suggestions: s }; },
  async sell_gift_card({ amount, recipientName, message }) { const p = DIGITAL_PRODUCTS['gift_card_' + amount]; return { product: p.name, price: p.price, checkoutUrl: 'https://hafsanoreen.com/shop?product=gift_card_' + amount, message: 'Gift card for ' + (recipientName || 'your loved one') }; },
  async sell_preset({ pack }) { const p = DIGITAL_PRODUCTS[pack === 'complete' ? 'preset_pack_pro' : 'preset_pack']; return { product: p.name, price: p.price, description: p.description, checkoutUrl: 'https://hafsanoreen.com/shop?product=' + (pack === 'complete' ? 'preset_pack_pro' : 'preset_pack') }; },
  async sell_wall_art({ size }) { const p = DIGITAL_PRODUCTS['wall_art_' + size] || DIGITAL_PRODUCTS.wall_art_8x10; return { product: p.name, price: p.price, checkoutUrl: 'https://hafsanoreen.com/shop?product=wall_art_' + size }; },
  async sell_print_product({ product: k }) { const p = DIGITAL_PRODUCTS[k]; return { product: p.name, price: p.price, checkoutUrl: 'https://hafsanoreen.com/shop?product=' + k }; },
  async print_recommender({ sessionType }) { return { recommendations: [{ ...DIGITAL_PRODUCTS.album_standard, reason: 'Perfect for your session.' }, { ...DIGITAL_PRODUCTS.wall_art_8x10, reason: 'Classic fine art print.' }] }; },
  async mini_session_filler({ season }) { return { message: 'Mini sessions: $225 for 20 min, 10 frames.', price: 225 }; },
  async photo_enhance({ photoData, style = 'cinematic', instructions }) { const sp = { cinematic: 'Edit with cinematic color grading: warm highlights, deep shadows, teal-orange tones, film grain, professional retouching, studio lighting.', golden_hour: 'Edit with golden hour warmth: soft golden light, warm amber tones, gentle glow, dreamy atmosphere.', moody_film: 'Edit with moody film aesthetic: desaturated, deep blacks, soft contrast, vintage grain, matte finish.', light_airy: 'Edit with light and airy style: bright, pastel tones, soft whites, clean and fresh.', 'b&w_fine_art': 'Convert to fine art black and white: rich tonal range, dramatic contrast, gallery quality.', studio_portrait: 'Edit with professional studio lighting: Rembrandt lighting, soft shadows, catchlight in eyes, smooth skin retouching.' }; const prompt = (sp[style] || sp.cinematic) + (instructions ? ' Additional: ' + instructions : ''); const r = await editImage(photoData, prompt); return { editedImages: r.images, description: r.text || 'Your enhanced photo is ready.', style, product: DIGITAL_PRODUCTS.photo_enhance.name, price: DIGITAL_PRODUCTS.photo_enhance.price }; },
  async photo_transform({ photoData, style = 'dramatic_studio', background, instructions }) { const sp = { dramatic_studio: 'Transform with dramatic studio lighting: strong key light, rim lighting, dark background, editorial quality.', fine_art: 'Transform into fine art: painterly quality, artistic composition, museum-worthy.', editorial: 'Transform with editorial magazine style: bold composition, fashion lighting, high-end quality.', vintage_film: 'Transform with vintage film aesthetic: 1970s tones, soft focus edges, warm color cast.', fantasy: 'Transform with fantasy aesthetic: ethereal lighting, magical atmosphere, dreamlike quality.' }; let prompt = sp[style] || sp.dramatic_studio; if (background === 'remove') prompt += ' Remove background completely.'; else if (background) prompt += ' Replace background with: ' + background; if (instructions) prompt += ' Additional: ' + instructions; const r = await editImage(photoData, prompt); return { transformedImages: r.images, description: r.text || 'Your transformed photo is ready.', style, product: DIGITAL_PRODUCTS.photo_enhance_pro.name, price: DIGITAL_PRODUCTS.photo_enhance_pro.price }; },
  async analyze_photo({ photoData, purpose = 'improvement' }) { const p = { improvement: 'Analyze and suggest improvements: lighting, composition, color, retouching.', style_match: 'Analyze style and recommend matching package.', package_recommend: 'Based on this photo, recommend best package and add-ons.', print_ready: 'Analyze for print readiness: resolution, color space, composition.' }; return { analysis: await analyzeImage(photoData, p[purpose] || p.improvement), purpose }; },
  async mood_board_gen({ sessionType, style, colors, location }) { return { concept: 'Mood board for ' + sessionType + ' session. Style: ' + (style || 'cinematic') + '. Colors: ' + (colors || 'warm neutrals') + '. Location: ' + (location || 'outdoor') + '.', note: 'Visual mood board will be sent to your email.' }; },
  async generate_save_date({ names, date, style }) { return { concept: 'Save-the-Date for ' + names + ' \u2014 ' + date + '. Style: ' + (style || 'cinematic romance') + '.', price: 350, product: DIGITAL_PRODUCTS.save_date_video.name }; },
  async what_to_wear({ sessionType, location, season, peopleCount }) { return { guide: 'For your ' + sessionType + ' session: Palette soft neutrals (cream, taupe, sage, dusty rose). Avoid logos, neon, busy patterns. Textures: linen, cotton, knits.' + (peopleCount > 1 ? ' Coordinate 2-3 colors across the group.' : ''), product: DIGITAL_PRODUCTS.style_guide.name, price: DIGITAL_PRODUCTS.style_guide.price }; },
  async caption_generator({ photoDescription, platform = 'instagram', tone = 'warm' }) { return { caption: 'Every moment tells a story. This one whispered ' + photoDescription + '. #HafsaNoreenPhotography', platform }; },
  async blog_generator({ topic, sessionType }) { return { draft: '# ' + topic + '\n\nEvery ' + sessionType + ' session has its own heartbeat.' }; },
  async email_drafter({ purpose, clientName, details }) { const d = { inquiry_reply: 'Dear ' + clientName + ', thank you for reaching out! ' + (details || ''), booking_confirm: 'Dear ' + clientName + ', your session is confirmed! ' + (details || ''), pre_session: 'Dear ' + clientName + ', your session is almost here! ' + (details || ''), post_session: 'Dear ' + clientName + ', sneak peek inside! ' + (details || ''), follow_up: 'Dear ' + clientName + ', just checking in! ' + (details || ''), review_request: 'Dear ' + clientName + ', your words mean the world! ' + (details || '') }; return { email: d[purpose] || d.inquiry_reply }; },
  async review_responder({ reviewText, rating, clientName }) { return { response: rating >= 4 ? 'Dear ' + clientName + ', thank you from the bottom of my heart!' : 'Dear ' + clientName + ', thank you for your feedback. I would love to make it right.' }; },
  async contract_generator({ clientName, sessionType, date, package: pkg }) { return { contract: 'PHOTOGRAPHY SERVICES AGREEMENT\n\nClient: ' + clientName + '\nSession: ' + sessionType + '\nDate: ' + date + '\nPackage: ' + (pkg || 'TBD') }; },
  async gallery_arranger({ sessionType, photoCount }) { return { suggestion: 'For ' + sessionType + ' with ' + photoCount + ' photos: Narrative flow \u2014 Getting Ready, Details, Portraits, Golden Hour, Closing.' }; },
  async client_ltv_scorer({ clientEmail }) { return { score: 'high', reason: 'Strong rebooking potential.' }; },
  async pricing_optimizer({ sessionType, season }) { const base = PACKAGES[sessionType]?.price || 0; return { currentPrice: base, suggestedPrice: Math.round(base * (season === 'summer' || season === 'fall' ? 1.1 : 1.0)) }; },
  async seasonal_predictor({ month }) { return { prediction: (month || 'Upcoming') + ' sees high demand for family and maternity.' }; },
  async brand_outreach({ brandName }) { return { outreach: 'Collaboration inquiry for ' + brandName + '.' }; },
  async competitor_monitor({ competitorUrl }) { return { analysis: 'Analysis for ' + competitorUrl + ' will be sent to dashboard.' }; },
  async retainer_nudger({ bookingId, daysOverdue }) { return { message: 'Retainer nudge for booking #' + bookingId + (daysOverdue ? ' (' + daysOverdue + ' days)' : '') }; },
  async abandoned_recovery({ clientEmail, sessionType, daysSince }) { return { message: 'Still interested in ' + sessionType + ' sessions? ' + (daysSince ? daysSince + ' days ago.' : 'Recently.') }; },
  async anniversary_rebooker({ clientEmail, lastSessionDate, lastSessionType }) { return { message: 'Almost a year since your ' + lastSessionType + ' session on ' + lastSessionDate + '! Time for the next chapter?' }; },
  async multi_lang_booking({ language, message }) { return { reply: 'Thank you for your message in ' + language + '! I can help you book the perfect session.' }; },
  async vendor_matchmaker({ vendorType, location }) { return { vendors: 'Trusted ' + vendorType + ' partners in ' + location + ' \u2014 list sent to your email.' }; },
  async venue_preview({ venueName }) { return { preview: venueName + ' is beautiful! Best angles: golden hour window, arched entrance, garden path.' }; },
  async headshot_booker({ clientName, clientEmail, urgency }) { return { booked: true, message: 'Headshot for ' + clientName + ' \u2014 ' + (urgency === 'rush' ? 'rush 48h' : 'standard 1 week') + '. Calendar invite sent!' }; },
  async mode_manager({ mode }) { const rm = require('../recovery-mode'); if (mode === 'recovery') rm.activate(); else rm.deactivate(); return { mode, status: 'updated' }; },
  async stock_submit({ photoData, platform, keywords }) { return { submitted: true, message: 'Submitted to ' + (platform || 'stock') + ' with keywords: ' + (keywords || 'photography') }; },
  async background_remover({ photoData, newBackground }) { const prompt = newBackground === 'remove' ? 'Remove background completely. Clean white background.' : 'Replace background with: ' + newBackground + '. Blend naturally.'; const r = await editImage(photoData, prompt); return { processedImages: r.images, description: r.text || 'Background processed.' }; }
};
module.exports = toolHandlers;
